### ISSUE TITLE
Apparently Windows Security is freaking out claiming that the program is a virus

### ISSUE THREAD

**Issue by GoatWalker** [GDX-X/PFS-BatchKit-Manager#12]
I know that it's obviously a false positive but Windows Security is freaking out, refusing to download the zip because it claims there is a virus in the zip. I know that you can just turn it off when it gets too whiny, I just wanted to let y'all know about this.

**Comment by GDX-X** [comment]
Yes, I've seen that too probably because of wget or busybox. Anyway, all the programs used in my script are open source. 

An update will be coming soon with new stuff!

**Comment by israpps** [comment]
Wget and NBD client `*.sys` files are the common culprits
