### ISSUE TITLE
hdd#:: partition not found: GAME_NAME while renaming files.

### ISSUE THREAD

**Issue by regulardude400** [GDX-X/PFS-BatchKit-Manager#13]
When trying to rename a file I have the HDD mounted through the NBD server and it mounts fine and all.  However when I try to manually or automatically rename the files, I get the error in the title.  I have made sure that I have followed the steps to get it working.  Thanks for making this program.  I may just have to mount the hdd to my pc locally in order to get it to work but if it works by doing that, I am eternally grateful.

**Comment by GDX-X** [comment]
Hey, Does it do this for all games or just one?

**Comment by regulardude400** [comment]
Thanks for the really quick response.  It does it for all games. I tried with the hdd plugged in directly to my pc and via the NDB server.  Here is a sample of the output when trying to rename the games automatically.

SLUS_201.59.Dave
Mirra Freestyle BMX 2
Rename to original Title: Dave Mirra Freestyle BMX 2
hdd4:: partition not found: "Mirra Freestyle BMX 2".
hdd4:: partition not found: "SLUS_201.59.Dave".


SLUS_204.86.Marvel
vs Capcom 2
Rename to original Title: Marvel vs Capcom 2
hdd4:: partition not found: "vs Capcom 2".
hdd4:: partition not found: "SLUS_204.86.Marvel".

**Comment by GDX-X** [comment]
Mhh strange can you go to PFS Batchkit > Advanced menu > HDDMagement Show Partition Information > Show PS2 Games Partitions Table And send me the partition name

**Comment by regulardude400** [comment]
Scanning for Playstation 2 HDDs:
----------------------------------------------------
        hdd4: 953867 MB, formatted Playstation 2 HDD


Partition PS2 Games List:
----------------------------------------------------
0x1337 00540000.:  3   640MB PP.HDLX-00002..TIMESPLITTERS_2
0x1337 00680000.:  3   640MB PP.HDL.SLUS_200.47.GAUNTLET - D
0x1337 007c0000.:  2   640MB PP.HDL.SLUS_200.66.HALF LIFE
0x1337 00900000.:  2   640MB PP.HDL.SLUS_201.59.Dave Mirra F
0x1337 00a40000.:  3   640MB PP.HDL.SLUS_202.12.BLOODY ROAR
0x1337 00b80000.:  3   640MB PP.HDL.SLUS_202.87.GUILTY GEAR
0x1337 00cc0000.:  2   640MB PP.HDL.SLUS_203.06.CONTRA - SHA
0x1337 00e00000.:  1   256MB PP.HDL.SLUS_204.86.Marvel vs Ca
0x1337 00e80000.:  6  3712MB PP.HDL.SCUS_971.02.Gran Turismo
0x1337 015c0000.:  4  1792MB PP.HDL.SCUS_971.11.Dark Cloud (
0x1337 01940000.:  3  1408MB PP.HDL.SCUS_971.24.Jak and Daxt
0x1337 01c00000.:  3  4352MB PP.HDL.SCUS_972.13.Dark Cloud 2
0x1337 02480000.:  6  3456MB PP.HDL.SCUS_972.31.Arc The Lad
0x1337 02b40000.:  6  4480MB PP.HDL.SCUS_972.34.Jampack - Wi
0x1337 03400000.:  4  3840MB PP.HDL.SCUS_972.35.Jampack - Wi
0x1337 03b80000.:  6  4224MB PP.HDL.SCUS_972.65.Jak II
0x1337 043c0000.:  6  4480MB PP.HDL.SCUS_972.80.Jampack - Su
0x1337 04b80000.:  6  4480MB PP.HDL.SCUS_972.81.Jampack - Su
0x1337 05440000.:  6  3200MB PP.HDL.SCUS_973.12.Jampack - Wi
0x1337 05b80000.:  5  3968MB PP.HDL.SCUS_973.13.Jampack - Wi
0x1337 06340000.:  7  5120MB PP.HDL.SCUS_973.28.Gran Turismo
0x1337 06b40000.:  7  4352MB PP.HDL.SCUS_973.30.Jak 3
0x1337 07540000.:  7  8192MB PP.HDL.SCUS_973.99.God of War (
0x1337 07dc0000.:  6  4480MB PP.HDL.SCUS_974.02.Killzone (US
0x1337 08d80000.:  4  3072MB PP.HDL.SCUS_974.06.Jampack Demo
0x1337 09480000.:  5  3328MB PP.HDL.SCUS_974.10.Jampack Demo
0x1337 09b00000.:  5  3456MB PP.HDL.SCUS_974.17.Jampack Demo
0x1337 0a1c0000.:  7  4352MB PP.HDL.SCUS_974.18.Jampack Demo
0x1337 0a9c0000.:  6  2560MB PP.HDL.SCUS_974.19.Jampack Demo
0x1337 0af40000.:  6  3840MB PP.HDL.SCUS_974.20.Jampack Demo
0x1337 0b6c0000.:  5  3328MB PP.HDL.SCUS_974.55.Holiday 2004
0x1337 0bd40000.:  4  2432MB PP.HDL.SCUS_974.56.Holiday 2004
0x1337 0c200000.:  4  8192MB PP.HDL.SCUS_974.81.God of War I
0x1337 0ca00000.:  4  4224MB PP.HDL.SCUS_974.91.Jampack Demo
0x1337 0da40000.:  7  4224MB PP.HDL.SCUS_974.92.Jampack Demo
0x1337 0e280000.:  6  3712MB PP.HDL.SCUS_974.93.Jampack Demo
0x1337 0e9c0000.:  4  3712MB PP.HDL.SCUS_974.94.Jampack Demo
0x1337 0f100000.:  4  2176MB PP.HDL.SCUS_975.01.Ape Escape 3
0x1337 0f540000.:  6  4480MB PP.HDL.SCUS_975.28.Holiday 2005
0x1337 0fe00000.:  4  4352MB PP.HDL.SCUS_975.29.Holiday 2005
0x1337 10680000.:  3  2816MB PP.HDL.SCUS_975.64.Jampack Demo
0x1337 10c00000.:  3  2432MB PP.HDL.SCUS_975.65.Jampack Demo
0x1337 110c0000.:  7  3584MB PP.HDL.SLUS_200.35.Baldurs Gate
0x1337 117c0000.:  6  4480MB PP.HDL.SLUS_200.62.Grand Theft
0x1337 11f80000.:  6  4480MB PP.HDL.SLUS_201.44.Metal Gear S
0x1337 12840000.:  5  2176MB PP.HDL.SLUS_202.20.Dead to Righ
0x1337 12d80000.:  6  4224MB PP.HDL.SLUS_202.30.Max Payne (U
0x1337 135c0000.:  2   256MB PP.HDL.SLUS_202.46.Capcom vs SN
0x1337 13640000.:  4   768MB PP.HDL.SLUS_202.53.The Mummy Re
0x1337 137c0000.:  4  2560MB PP.HDL.SLUS_202.67.Dot Hack Par
0x1337 13cc0000.:  5  2816MB PP.HDL.SLUS_202.94.Gitaroo Man
0x1337 14240000.:  5  3968MB PP.HDL.SLUS_203.07.Burnout
0x1337 14a00000.:  2  3072MB PP.HDL.SLUS_203.09.Jade Cocoon
0x1337 15000000.:  3  4352MB PP.HDL.SLUS_203.12.Final Fantas
0x1337 15880000.:  3  1024MB PP.HDL.SLUS_203.27.Aggressive I
0x1337 15a80000.:  6  4352MB PP.HDL.SLUS_203.35.Mat Hoffmans
0x1337 16300000.:  3  2048MB PP.HDL.SLUS_204.17.Grandia Xtre
0x1337 16700000.:  5  3968MB PP.HDL.SLUS_204.36.Guilty Gear
0x1337 16ec0000.:  4  1408MB PP.HDL.SLUS_204.93.Gungrave (US
0x1337 17180000.:  5  3968MB PP.HDL.SLUS_204.97.Burnout 2 -
0x1337 17940000.:  6  2304MB PP.HDL.SLUS_205.20.The Lord of
0x1337 17dc0000.:  4  3712MB PP.HDL.SLUS_205.52.Grand Theft
0x1337 18500000.:  5  6272MB PP.HDL.SLUS_205.54.Metal Gear S
0x1337 18940000.:  5  3584MB PP.HDL.SLUS_205.62.Dot Hack Par
0x1337 19840000.:  7  3712MB PP.HDL.SLUS_205.63.Dot Hack Par
0x1337 19f80000.:  6  4352MB PP.HDL.SLUS_205.64.Dot Hack Par
0x1337 1a800000.:  5  3968MB PP.HDL.SLUS_205.78.The Lord of
0x1337 1afc0000.:  3  1408MB PP.HDL.SLUS_205.91.Dragon Ball
0x1337 1b280000.:  5  3584MB PP.HDL.SLUS_206.37.Chessmaster
0x1337 1b980000.:  5  2176MB PP.HDL.SLUS_206.39.Def Jam - Ve
0x1337 1bdc0000.:  4  1792MB PP.HDL.SLUS_206.85.Ape Escape 2
0x1337 1c140000.:  6  4480MB PP.HDL.SLUS_207.70.The Lord of
0x1337 1ca00000.:  4  4224MB PP.HDL.SLUS_207.73.Legacy of Ka
0x1337 1d240000.:  6  4480MB PP.HDL.SLUS_207.79.Dragon Ball
0x1337 1db00000.:  3  1280MB PP.HDL.SLUS_207.95.Bloody Roar
0x1337 1dd80000.:  6  4352MB PP.HDL.SLUS_208.01.Midway Arcad
0x1337 1e600000.:  2  1280MB PP.HDL.SLUS_208.05.Yu Yu Hakush
0x1337 1e880000.:  5  2560MB PP.HDL.SLUS_208.14.Max Payne 2
0x1337 1ed80000.:  4  2048MB PP.HDL.SLUS_208.41.NFL Street (
0x1337 1f180000.:  6  4480MB PP.HDL.SLUS_208.43.Dead to Righ
0x1337 1f940000.:  6  4480MB PP.HDL.SLUS_209.15.Metal Gear S
0x1337 20300000.:  5  4352MB PP.HDL.SLUS_209.46.Grand Theft
0x1337 20b80000.:  2  2304MB PP.HDL.SLUS_209.50.Capcom Fight
0x1337 21000000.:  5  3968MB PP.HDL.SLUS_209.63.Final Fantas
0x1337 217c0000.:  2  2176MB PP.HDL.SLUS_209.71.Metal Slug 4
0x1337 21c00000.:  2  2176MB PP.HDL.SLUS_209.90.Metal Slug 5
0x1337 22040000.:  4  1920MB PP.HDL.SLUS_209.94.Fullmetal Al
0x1337 22400000.:  3  1792MB PP.HDL.SLUS_209.96.The King of
0x1337 22780000.:  4  2688MB PP.HDL.SLUS_209.97.Midway Arcad
0x1337 22cc0000.:  6  4480MB PP.HDL.SLUS_209.98.Dragon Ball
0x1337 23480000.:  6  4608MB PP.HDL.SLUS_210.04.Def Jam - Fi
0x1337 23d80000.:  4  3840MB PP.HDL.SLUS_210.20.Gungrave - O
0x1337 24600000.:  6  4480MB PP.HDL.SLUS_210.27.The Lord of
0x1337 24dc0000.:  4  2816MB PP.HDL.SLUS_210.50.Burnout 3 -
0x1337 25440000.:  6  4480MB PP.HDL.SLUS_210.77.Gauntlet - S
0x1337 25d00000.:  3  2560MB PP.HDL.SLUS_210.94.Midway Arcad
0x1337 26200000.:  4  3456MB PP.HDL.SLUS_210.96.Ape Escape -
0x1337 268c0000.:  6  4096MB PP.HDL.SLUS_211.18.NFL Street 2
0x1337 270c0000.:  6  3328MB PP.HDL.SLUS_212.27.Dragon Ball
0x1337 27740000.:  5  3584MB PP.HDL.SLUS_212.58.Dot Hack G U
0x1337 27e40000.:  6  4480MB PP.HDL.SLUS_212.69.Bully
0x1337 28700000.:  3  1792MB PP.HDL.SLUS_212.74.OutRun 2006
0x1337 28a80000.:  4  2944MB PP.HDL.SLUS_213.16.Capcom Class
0x1337 29040000.:  7  4224MB PP.HDL.SLUS_213.34.Grandia III
0x1337 29880000.:  5  4096MB PP.HDL.SLUS_213.45.Grandia III
0x1337 2a080000.:  4  1536MB PP.HDL.SLUS_213.58.Naruto - Ult
0x1337 2a380000.:  5  2176MB PP.HDL.SLUS_213.65.The King of
0x1337 2a7c0000.:  4  2944MB PP.HDL.SLUS_213.74.Marvel - Ult
0x1337 2ad80000.:  4  3840MB PP.HDL.SLUS_214.23.Grand Theft
0x1337 2b500000.:  5  2944MB PP.HDL.SLUS_214.41.Dragon Ball
0x1337 2bac0000.:  4  3200MB PP.HDL.SLUS_214.73.Capcom Class
0x1337 2c100000.:  5  3968MB PP.HDL.SLUS_214.88.Dot Hack GU
0x1337 2c8c0000.:  7  4224MB PP.HDL.SLUS_214.89.Dot Hack GU
0x1337 2d100000.:  2  1536MB PP.HDL.SLUS_215.03.God Hand (US
0x1337 2d400000.:  3  1408MB PP.HDL.SLUS_215.50.Metal Slug A
0x1337 2d6c0000.:  5  3968MB PP.HDL.SLUS_215.75.Naruto - Ult
0x1337 2de80000.:  5  3968MB PP.HDL.SLUS_215.90.Grand Theft
0x1337 2e640000.:  6  4096MB PP.HDL.SLUS_216.52.Guilty Gear
0x1337 2ee40000.:  5  1664MB PP.HDL.SLUS_216.53.Heavenly Gua
0x1337 2f180000.:  5  2944MB PP.HDL.SLUS_216.78.Dragon Ball
0x1337 2f740000.:  3  2432MB PP.HDL.SLUS_216.87.The King of
0x1337 2fc00000.:  1  2048MB PP.HDL.SLUS_217.20.Arcana Heart
0x1337 30000000.:  5  3968MB PP.HDL.SLUS_217.27.Naruto - Ult
0x1337 307c0000.:  3  1408MB PP.HDL.SLUS_217.55.Are You Smar
0x1337 30a80000.:  4  2048MB PP.HDL.SLUS_217.75.The Mummy -
0x1337 30e80000.:  6  3712MB PP.HDL.SLUS_218.47.Guilty Gear
0x1337 315c0000.:  5  3968MB PP.HDL.SLUS_218.62.Naruto Shipp
0x1337 31d80000.:  4  1664MB PP.HDL.SLUS_218.79.Marvel - Ult
0x1337 320c0000.:  4  1920MB PP.HDL.SLUS_219.15.The Lord of
0x1337 32480000.:  5  7936MB PP.HDL.SLUS_217.69.Yakuza 2 (US
0x1337 32c00000.:  3  4224MB PP.HDL.SLUS_213.48.Yakuza (USA)
0x1337 33c40000.:  6  2560MB PP.HDL.SLUS_206.77.XIII (USA)
0x1337 34140000.:  4  1664MB PP.HDL.SLUS_209.77.Virtua Quest
0x1337 34480000.:  4  1536MB PP.HDL.SLUS_206.16.Virtua Fight
0x1337 34780000.:  5  3712MB PP.HDL.SCUS_971.01.Twisted Meta
0x1337 34ec0000.:  7  4608MB PP.HDL.SLUS_203.14.TimeSplitter
0x1337 356c0000.:  7  4352MB PP.HDL.SLUS_210.59.Tekken 5 (US
0x1337 35fc0000.:  6  2688MB PP.HDL.SLUS_203.28.Tekken 4 (US
0x1337 36580000.:  3  3328MB PP.HDL.SLUS_209.49.Street Fight
0x1337 36c00000.:  3  4608MB PP.HDL.SLUS_213.17.Street Fight
0x1337 37500000.:  6  4480MB PP.HDL.SLUS_212.40.Star Wars -
0x1337 37cc0000.:  7  4224MB PP.HDL.SLUS_212.16.Soulcalibur
0x1337 38600000.:  4  4224MB PP.HDL.SLUS_206.43.Soulcalibur
0x1337 38e40000.:  7  4608MB PP.HDL.SLUS_207.18.Sonic Heroes
0x1337 39640000.:  3  1408MB PP.HDL.SLUS_205.09.Sega Soccer
0x1337 39a00000.:  4  3840MB PP.HDL.SLUS_215.42.Sega Genesis
0x1337 3a180000.:  3  1408MB PP.HDL.SLUS_210.09.Sega Classic
0x1337 3a440000.:  5  2944MB PP.HDL.SLUS_216.29.Samurai Shod
0x1337 3aa00000.:  3  3200MB PP.HDL.SLUS_213.43.Samurai Cham
0x1337 3b040000.:  7  3328MB PP.HDL.SLUS_206.01.Rayman 3 - H
0x1337 3b6c0000.:  7  4352MB PP.HDL.SLUS_201.38.Rayman 2 - R
0x1337 3bec0000.:  6  4096MB PP.HDL.SCUS_971.99.Ratchet and
0x1337 3c740000.:  7  4224MB PP.HDL.SCUS_973.53.Ratchet and
0x1337 3cf80000.:  3  1792MB PP.HDL.SCUS_976.15.Ratchet and
0x1337 3d300000.:  4  3200MB PP.HDL.SCUS_972.68.Ratchet and
0x1337 3d940000.:  7  4224MB PP.HDL.SCUS_974.65.Ratchet - De
0x1337 3e180000.:  3  1408MB PP.HDL.SLUS_216.92.Puzzle Quest
0x1337 3e440000.:  6  4096MB PP.HDL.SLUS_211.94.Phantasy Sta
0x1337 3ec40000.:  7  4352MB PP.HDL.SCUS_971.67.PaRappa the
0x1337 3f440000.:  6  3456MB PP.HDL.SLUS_212.19.Pac-Man Worl
0x1337 3fb80000.:  4  1152MB PP.HDLX-00002..PAC_MAN_WORLD_2
0x1337 3fdc0000.:  5  3968MB PP.HDLX-00002..YS___THE_ARK_OF_
0x1337 40580000.:  2   384MB PP.HDL.Puzzle Challenge - Cross
0x1337 40640000.:  3   640MB PP.HDL.Street Fighter EX3 (USA)
0x1337 40780000.:  3   640MB PP.HDL.Tekken Tag Tournament (U
0x1337 408c0000.:  2   384MB PP.HDL.Tetris Worlds (USA)
0x1337 40980000.:  3   640MB PP.HDLX-00000..TIMESPLITTERS_2
----------------------------------------------------

Press any key to continue . . .

**Comment by GDX-X** [comment]
I think I know why he doesn't rename himself. because the games were installed with an old version of HDL_dump so the format of the partitions is no longer the same I will try to see if I can do something to convert them to the new format

**Comment by regulardude400** [comment]
Thanks so much. :) I appreciate all of your help.

**Comment by GDX-X** [comment]
can you export ps2 games list? to check something > Advanced menu > Game Management > Export game list

**Comment by regulardude400** [comment]
[GamelistPS2.txt](https://github.com/GDX-X/PFS-BatchKit-Manager/files/8356588/GamelistPS2.txt)

**Comment by GDX-X** [comment]
this little script should rename all your games automatically

[RenamePS2Game.zip](https://github.com/GDX-X/PFS-BatchKit-Manager/files/8356626/RenamePS2Game.zip)

**Comment by GDX-X** [comment]
I forgot to edit the Rename.bat and remove the word `echo` in lines 14 and 15 and run it as admin

**Comment by regulardude400** [comment]
Thank you very much! I will give the script a try.

**Comment by GDX-X** [comment]
Glad it helped you ;)
