### ISSUE TITLE
I can't put modded games on ps2 (Mario 64; Dragon ball bodokai; crossover mods)

### ISSUE THREAD

**Issue by LuisFmag** [GDX-X/PFS-BatchKit-Manager#17]
![Screenshot_18](https://user-images.githubusercontent.com/83992043/167216187-8cc23959-c8d5-4b7d-a63d-f446f9e4e7ae.png)

**Comment by GDX-X** [comment]
Hey, Yes a similar problem has already been opened

this comes from the modified iso you have to do this to have it recognized

you must then modify the SYSTEM.CNF and replace cdrom1: by cdrom0: so that it is recognized as a PS2 game

the steps to do it

    Extract the files from the iso

    Edit the SYSTEM.CNF

    Replace cdrom1: by cdrom0:

    Download ultraiso

    In ultraiso Do File > New > PS2 DVD Image and fetch the SYSTEM.CNF file of the iso you extracted
    Note: PS2 CD IMAGE is only for games that does not exceed 1gb

    Do File > Save as

**Comment by israpps** [comment]
> Hey, Yes a similar problem has already been opened
> 
> this is from the modified iso, you need to modify a file to get it recognized
> 
> you must then modify the SYSTEM.CNF and replace cdrom1: by cdrom0: so that it is recognized as a PS2 game
> 
> the steps to do it
> 
> ```
> Extract the files from the iso
> 
> Edit the SYSTEM.CNF
> 
> Replace cdrom1: by cdrom0:
> 
> Download ultraiso
> 
> In ultraiso Do File > New > PS2 DVD Image and fetch the SYSTEM.CNF file of the iso you extracted
> Note: PS2 CD IMAGE is only for games that does not exceed 1gb
> 
> Do File > Save as
> ```

keep in mind that hdl-dump also expects the image to be on Playstation format...

I made a PR to HDLDump so the `system.cnf` parser marks the image as valid if `cdrom1:\` is passed

But the filesystem requirement is something that shouldn't be removed
