### ISSUE TITLE
Can't rename

### ISSUE THREAD

**Issue by kruuth** [GDX-X/PFS-BatchKit-Manager#18]
I'm attempting to rename a game, in this case it is called "SLPM_623.84" and when I do this happens:
`Game Selected "SLPM_623.84"
----------------------------------------------------
Renaming...
"SLPM_623.84"

hdd2:: partition with such name already exists: "SLPM_623.84".
hdd2:: partition with such name already exists: "PFSBATCHKIT".
"Sega Ages 2500 Series Vol.04 - Space Harrier"
Completed...
----------------------------------------------------
Renaming Completed...`

This won't actually rename the game.  Tried running this as admin and no change.  This is under Win10 with a SATA drive.

**Comment by GDX-X** [comment]
He say hdd2:: partition with such name already exists

If you installed your games with an old version of hdl_dump or winhiip there is a limitation in the name of the partitions I advise you to delete the games that are not renamed and reinstall them

it's the only way

**Comment by israpps** [comment]
> He say hdd2:: partition with such name already exists
> 
> If you installed your games with an old version of hdl_dump or winhiip there is a limitation in the name of the partitions I advise you to delete the games that are not renamed and reinstall them
> 
> it's the only way

The partition with such name already exists error can also happen if the name length is larger than 17 and you didn't change the name on the first 17 chars...
Since those 17 chars will get reflected on the partition name

**Comment by GDX-X** [comment]
No You can have the same game name only with the new partition name if the games were installed with an old version of hdl_dump 

the partition name will be PP.HDL.NAMEGAME or PP.SLUS-0000.HDLX
while with the new name of the partitions it will be PP.SLUS-12345..GAMENAME 

So with the unique gameid of the game the partition cannot look like another

**Comment by kruuth** [comment]
Ok.  I will do that.
