### ISSUE TITLE
Are there any plans to make a GUI version one day?

### ISSUE THREAD

**Issue by sjdo** [GDX-X/PFS-BatchKit-Manager#20]
Are there any plans to make a GUI version one day?

**Comment by israpps** [comment]
this script is heavily based on windows batch file..

And having it all in one file makes it hard to read...

However, if @GDX-X is willing to suffer that transition, then a cross platform UI made on wxWidgets Should be possible........

**Comment by GDX-X** [comment]
Hey, At the moment it's not in my plans but I could think about it. First I will finish adding some additional features in 
PFS Batchkit Manager, then try to see how to create a GUI. I intended to make it cross-platform but some programs are not open source and cannot be ported to be used on linux for example.

the batch code is extremely simple which allows me to add a lot of things in a short time.

**Comment by israpps** [comment]
> Hey, At the moment it's not in my plans but I could think about it. First I will finish adding some additional features in PFS Batchkit Manager, then try to see how to create a GUI. I intended to make it cross-platform but some programs are not open source and cannot be ported to be used on linux for example.
> 
> the batch code is extremely simple which allows me to add a lot of things in a short time.

If you're looking for cross platform then WxWidgets is your friend...

PCSX2, HDL Batch installer and Pops VCD manager are made on it

I can help...

**Comment by GDX-X** [comment]
After thinking about it, it won't be useful to make a GUI because the APA partition system will become useless in the future with the support of exFAT.
