### ISSUE TITLE
maxcso multithread

### ISSUE THREAD

**Issue by LuckyStarShiRoku** [GDX-X/PFS-BatchKit-Manager#21]
maxcso supports multiple threads to speed up compression was wondering if the batch script could add the "--threads" argument to speed up compression.

**Comment by GDX-X** [comment]
I believe the --threads= argument doesn't work because I tried it and didn't notice any difference in speed

I have an i7-4790k
I did 
--threads=4
--threads=8

No speed difference
Try on your side to see if you have any difference
