### ISSUE TITLE
[Proposal]: replace cue2pops and binmerge

### ISSUE THREAD

**Issue by israpps** [GDX-X/PFS-BatchKit-Manager#23]
The idea would be to replace current cue2pops with [mine](https://github.com/israpps/cue2pops/releases)

and to replace binrmerge with [BinMerger](https://github.com/israpps/BinMerger/releases)

My custom Cue2POPS has some tweaks, and a progress report (in the form of bytes written and progress percentage)

and BinMerger should be faster than binmerge since it was made on C++

**Comment by GDX-X** [comment]
POPstarter is discontinued, I prefer to keep the tools as they are for the moment.
