### ISSUE TITLE
[ISSUE]: Script closes instantly

### ISSUE THREAD

**Issue by israpps** [GDX-X/PFS-BatchKit-Manager#25]
console output:
```console
C:\Users\Usuario\Desktop\PFS_BatchKit_Manager_v1.1.2>"!PFS-BatchKit-Manager.bat"
Checking for updates...

C:\Users\Usuario\Desktop\PFS_BatchKit_Manager_v1.1.2\TMP>
```

**Comment by Falumir** [comment]
There's a BAT folder required by the script that's not included in PFS_BatchKit_Manager_v1.1.5.zip. If you download the zip for the source code you can extract the BAT folder from it. Drop it in the same directory as the script and it should work fine.

@GDX-X  is it possible to make sure the BAT folder is included in the main zip file? I imagine it will clear up a lot of confusion.

**Comment by GDX-X** [comment]
The BAT file is included in all versions because without this file the script will not work

I guess it's an antivirus that removes it

**Comment by Falumir** [comment]
Sorry, I took another look and see what's happening here. It's included but is flagged as hidden. If someone just copies and pastes everything they can see from the zip out to a different folder odds are they'll probably miss it.

**Comment by GDX-X** [comment]
Ah! Yes, it is a hidden folder to prevent average user from copying files or others into it
