### ISSUE TITLE
Incorrect GameID fetched from ZSO

### ISSUE THREAD

**Issue by synrais** [GDX-X/PFS-BatchKit-Manager#29]
When transferring pre-converted zso images to HDD PFS-Batch cannot fetch the correct GameID for the following games.
I am pretty sure if you convert the iso to zso when transferring to HDD then the GameID is fine though.
I know that a limitation of HDLDump is it needs the original iso in the same folder as the zso, is this the case with PFS-Batch also to correctly transfer games?
I only noticed this when going thru the config files that failed to fetch due to their incorrect names. 
There may be more that fetch the incorrect region GameID as it is present in some titles, below Onimusha is an example of this.

1 - SLPM_657.48.Zoids - Struggle (Japan).zso
Title:    [SLPM_657.48.Zoids - Struggle (Japan)]
Gameid:   [SLPM_657ý48]
Region:   [NTSC-J]

2 - SLPS_252.61.Guilty Gear XX Reload - The Midnight Carnival (Japan Asia).zso
Title:    [SLPS_252.61.Guilty Gear XX Reload - The Midnight Carnival (Japan Asia)]
Gameid:   [HAAA_645345]
Region:   [NTSC-A]

3 - SLUS_201.89.Tokyo Xtreme Racer - Zero (USA).zso
Title:    [SLUS_201.89.Tokyo Xtreme Racer - Zero (USA)]
Gameid:   [SLUS_201_89]
Region:   [NTSC-U/C]

4 - SLUS_207.10.Onimusha - Blade Warriors (USA).zso
Title:    [SLUS_207.10.Onimusha - Blade Warriors (USA)]
Gameid:   [SLES_519_13]
Region:   [PAL]

**Comment by GDX-X** [comment]
The version of hdl_dump used by PFS Batchkit Manager can install the zso directly but I have to update it because the zso logic has changed

To solve your problem I advise you to convert the games directly during installation

An update will come soon maybe tomorrow if I have time to finish with a lot of improvement and functionality

**Comment by israpps** [comment]
> The version of hdl_dump used by PFS Batchkit Manager can install the zso directly but I have to update it because the zso logic has changed
> 
> To solve your problem I advise you to convert the games directly during installation
> 
> An update will come soon maybe tomorrow if I have time to finish with a lot of improvement and functionality

Don't rely on the return code of the program anymore after updating

Some of the code is doing weird things, making the program return abnormal value

**Comment by GDX-X** [comment]
Fixed in 1.1.3
