### ISSUE TITLE
PS1 Transfer issue 

### ISSUE THREAD

**Issue by Zongie** [GDX-X/PFS-BatchKit-Manager#30]
installing PS1 .VCD and it stops saying  regex couldent find ELF ID matching pattern for  game SLPS_024.14 
Medarot R any help would be greatly appriciated.

**Comment by GDX-X** [comment]
Thanks for the report I will check

**Comment by Zongie** [comment]
also it would be nice to be able to skip it if it wont install  just a suggestion

**Comment by Zongie** [comment]
i cut those games out of the pops folder  and now when installing ps1 games it just stops installing

**Comment by GDX-X** [comment]
I solved the two problems you mentioned.

It's two games in particular that aren't made the same way as other PS1 games.

I will post this update soon

**Comment by Zongie** [comment]
Also ff7 disc2 and 3 were red i don't remember what it said

**Comment by GDX-X** [comment]
if the hdl dump stops working it's your computer because i've never had a problem with it or some other program is causing it to crash

try it on a virtual machine or close all other running programs likely to cause it to crash

**Comment by Zongie** [comment]
alll good ur program has been the only one to not  crash on startup or just not work. thank you for this program . 
 idk how to run a VM  also dont know what would be causing it to crash

**Comment by GDX-X** [comment]
Fixed in 1.1.4
