### ISSUE TITLE
Cant uninstal a game

### ISSUE THREAD

**Issue by l-guille** [GDX-X/PFS-BatchKit-Manager#32]
First of all i want say sorry for my dumbness, but i couldnt find where i can remove a game i installed in my ps2 hard drive, its a ps2 game.

**Comment by GDX-X** [comment]
With wLaunchELF or OPL 

If you delete it from OPL, you must activate the write operation in the settings

**Comment by l-guille** [comment]
you mean, i delete the game with ulanchelf in the ps2? there is not a way to do in the batchkit?

**Comment by GDX-X** [comment]
currently you cannot. however there is a method but I advise against it for safety because it can corrupt the hard disk

**Comment by israpps** [comment]
Whatever method you use to delete the game 

Run HDDChecker afterwards just to be sure the won't be any surprises anytime soon
