### ISSUE TITLE
Program crashes when I attempt to transfer PS2 games.

### ISSUE THREAD

**Issue by Fighterbuilder** [GDX-X/PFS-BatchKit-Manager#37]
Whenever I attempt to transfer PS2 games to my HDD, the program instantly crashes after declining to change the default directory regardless of what other options I choose or which games I try to transfer to it. It closes so quickly I can't tell if it gives an error before it closes, and if there was a log saved, I couldn't find it. I was able to transfer PS1 games and OPL files just fine.

**Comment by GDX-X** [comment]
Mhh..
I will post an update that fixes a lot of things

If your problem persists I advise you to test on another computer if possible or a virtual machine

**Comment by Fighterbuilder** [comment]
Just tested it on a different computer and it actually worked this time! Still not sure what exactly was going wrong the first time though. Are there any logs saved during this process that I could look for?

**Comment by GDX-X** [comment]
No, unfortunately in batch it is difficult to make error logs

in my opinion, there is something that conflicts with.
maybe an antivirus?

It's hard to really know what's causing this as I've never had this issue.

for now i will say

1 - Antivirus
2 - Windows environment path

**Comment by Fighterbuilder** [comment]
I see. I do have Malwarebytes on my main PC; I'll try disabling it and trying again once I get home from work. I'll also take a look at the environment path if that doesn't work.

**Comment by Fighterbuilder** [comment]
Unfortunately disabling Malwarebytes didn't fix the problem, so now I'm left with the environment path. I don't really know what I should change here so I figured I'd at least post mine here in case you find something that could be causing problems.
Here's the user Path variables:
`%USERPROFILE%\AppData\Local\Microsoft\WindowsApps
C:\devkitPro\devkitPPC\bin
C:\devkitPro\devkitPPC\powerpc-eabi\bin
C:\Users\Ben\AppData\Roaming\npm`
And here are the system Path variables:
`C:\Python311\Scripts\
C:\Python311\
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
c:\devkitPro\msys2\usr\bin
%SystemRoot%\system32
%SystemRoot%
%SystemRoot%\System32\Wbem
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\
%SYSTEMROOT%\System32\OpenSSH\
C:\Program Files\dotnet\
C:\Program Files\nodejs\
C:\ProgramData\chocolatey\bin`

**Comment by GDX-X** [comment]
I believe you are missing this text in variable system

![810df2fe2ad263beda51aa5912038b65](https://user-images.githubusercontent.com/22562949/236584617-b8019b82-0477-4014-9d79-8b16fba96570.png)

**Comment by Fighterbuilder** [comment]
Nope, that's there right below it.
![image](https://user-images.githubusercontent.com/33814663/236584904-a8725c5a-4c4b-4821-bd59-66d457d5b8fc.png)
In the meantime though, I was able to set up a Windows 10 VM to use this on my main PC, and it seems to be working.

**Comment by GDX-X** [comment]
That one also in the system?

`ComSpec`
`%SystemRoot%\system32\cmd.exe`

**Comment by Fighterbuilder** [comment]
Yes, that variable is there as well.
Also, great to hear!

**Comment by GDX-X** [comment]
I was supposed to release the update this weekend but I didn't have time to finish what I had to do :D

As for your problem, there's probably something causing it to crash, but I don't know what.
