### ISSUE TITLE
PS2 games retain an HDLoader icon in HDDOSD after running "Update Partition Resources Header"

### ISSUE THREAD

**Issue by NinCollin** [GDX-X/PFS-BatchKit-Manager#38]
Having an odd issue; running "Update Partition Resources Header" and selecting Yes to update the 3D icon in HDDOSD does not actually update the icon for PS2 games (they retains the HDLoader icon)

The option isn't doing _nothing_ because the titles of the PS2 games get changed to match their fetched database name, but their icons don't get updated. 

I should mention that I'm using Windows 10 and mounting the drive over NBD

I should also note that I do not have FreeHDBoot installed; not sure if that makes a difference.

**Comment by GDX-X** [comment]
The database is small it does not contain a lot of icons so it is normal if it keeps the hd loader icon

**Comment by GDX-X** [comment]
Great! You only need the icons of your game saves that you can take with wLaunchELF
the icons available in the database are from my game saves or from people who have shared them with me

I will be happy to include them in the database

I also take the background color from game saves.

I had created a small script which allows to convert the colors for the hdd-osd but it is not intuitive at all it was mainly for testing

Currently, I am very busy with other tasks. I'm also preparing a big update for PFS Batchkit Manager with a complete new redump title database. it will contain 99% of all the titles for the games the missing 1% are games from the Asian region

**Comment by Fighterbuilder** [comment]
Sweet! Guess I know what I'll be working on when I get home from work lol
Where can I find the database btw? Or would you rather I send them to you directly?

**Comment by Fighterbuilder** [comment]
Also, is there a template for HDDOSD PSX icons? I'd like to take a crack at filling some of those gaps too.

**Comment by GDX-X** [comment]
the PSX has the same HDD-OSD except for the XMB menu but the XMB menu are png images at a specific size

The database is here: https://archive.org/details/hdd-osd-icons-pack

**Comment by NinCollin** [comment]
I'd be interesting in contributing too

Also, you said you take the background color from the game saves; is this taken from the icon.sys file? (I know for memory cards they're in a binary format instead of the text format used for HDDOSD) or do you get the background color exclusively from the icons? I'm mainly just curious if I should include the memory card's icon.sys when I send em to you

**Comment by Fighterbuilder** [comment]
Thanks!
> the PSX has the same HDD-OSD except for the XMB menu but the XMB menu are png images at a specific size

Oops, my bad... I meant to put PS1 here instead; I'm used to using the term PSX to refer to that. Had me confused there for a bit. I'm referring to the PS1 icons that show up in HDDOSD when installed as partitions, some of which have box art and a controller and others which just have a PS symbol model.

**Comment by GDX-X** [comment]
> Thanks!
> 
> > the PSX has the same HDD-OSD except for the XMB menu but the XMB menu are png images at a specific size
> 
> Oops, my bad... I meant to put PS1 here instead; I'm used to using the term PSX to refer to that. Had me confused there for a bit. I'm referring to the PS1 icons that show up in HDDOSD when installed as partitions, some of which have box art and a controller and others which just have a PS logo model.

Ah yes! :D
in the PS2 scene the terms used are:

PS1 = PS1
PS-X = PS1

PSX = PS2X DESR
PS2 = PS2

Yes there is a template in the PS1 folder of the database if I remember



> I'd be interesting in contributing too
> 
> Also, you said you take the background color from the game saves; is this taken from the memory card icon.sys file? (I know for memory cards they're in a binary format instead of the text format used for HDDOSD) or do you get the background color exclusively from the icons? I'm mainly just curious if I should include the memory card's icon.sys when I send em to you

Yes you can send everything if you can

**Comment by Fighterbuilder** [comment]
Awesome, thank you!

**Comment by Fighterbuilder** [comment]
So how should I send these to you?

**Comment by Fighterbuilder** [comment]
Also, should I rename any of the files, or should I leave them untouched and let you handle it?

**Comment by GDX-X** [comment]
You can upload them to google drive or others

for the names no need to rename them

**Comment by Fighterbuilder** [comment]
Cool! Yeah, I was comparing the files I ripped from my memory card with the files already in the database last night and was a bit confused/concerned when I noticed the different naming convention lol; I thought I was about to have to do a _lot_ of icon.sys hex editing 😅

**Comment by GDX-X** [comment]
More HDD-OSD Icons add in 1.1.8
