### ISSUE TITLE
Partition deletion not working

### ISSUE THREAD

**Issue by cryptblood1986** [GDX-X/PFS-BatchKit-Manager#39]
I deleted __.POPS partition says deleted. Then I check again and the partition is still there.

**Comment by GDX-X** [comment]
It looks like partition scheme corruption

I advise you to reformat your hard drive

**Comment by cryptblood1986** [comment]
I was able to delete the partition using a different program called PFS HDD manager by Leyed. Also mounting drives still appears to be broken on windows 10. Still opens up Quick Access instead.
