### ISSUE TITLE
BIN2VCD errors not handled for busybox

### ISSUE THREAD

**Issue by Br3ttl3y** [GDX-X/PFS-BatchKit-Manager#4]
If an error occurs for a file during [line 7306](https://github.com/GDX-X/PFS-BatchKit-Manager/blob/39fa8b5174223278a1673c5180fdbc1efede324f/PFS-BatchKit-Manager/!PFS-BatchKit-Manager.bat#L7306) there is no contingency to stop the batch process.

It simply acts as if nothing happens and continues to process the files.
If the user wants to try again, the BIN2VCD folder structure is in a confused state.
The Temp directory is removed and all progress is lost, if doing many files, a lot of time is lost.

Furthermore it seems that this error puts the next step in a confused state, the bin files never get moved to temp.  CUETOPOPS_2_3 errors and allows you to continue.

**Comment by GDX-X** [comment]
Thank you for your feedback, and sorry for the inconvenience

I think I fixed the bug an update will arrive soon with other improvements
