### ISSUE TITLE
-hide switch are not working

### ISSUE THREAD

**Issue by sergioroprado** [GDX-X/PFS-BatchKit-Manager#42]
Seems like theres a problem with the -hide switch on the script. I tryed multiple times, bus the function to hide the games from HDD-OSD are not working.

**Comment by GDX-X** [comment]
It works fine for me what is the name of the partition you are trying to hide?

**Comment by sergioroprado** [comment]
i'm using the PFS Batchkit to transfer my Ps2 games, and selecting the option for it to no show in HDD-OSD, but no matter what i do, all the games partitions always show up on HDD-OSD.

**Comment by GDX-X** [comment]
Ah yes hiding all the partitions does not work indeed

**Comment by GDX-X** [comment]
I just tried to hide everything it works without problem for me

Looks like you have a corruption of the apa chain at least I guess

**Comment by sergioroprado** [comment]
Thanks for the answer.  I mistakenly assumed that setting to "N" the option with the description "Allows you to launch your games from HDD-OSD", would hide my games from it.

I just got what I wanted.  I just had to edit the batch file by adding the "-hide" switch after both "*u4".  
If it's not too much trouble, it would be nice to have the option to hide games from the HDD-OSD.

**Comment by GDX-X** [comment]
Ahh I thought you were talking about the options already present however your idea is not bad I didn't think about it but the option already exists to hide everything

Advanced Menu > FHDB/HDD-OSD/PSBBN/XMB > Partition Management

**Comment by sergioroprado** [comment]
Thanks for the info man. I already moved almost 800gb of data two times already, trying to figure this out.
