### ISSUE TITLE
BIN To ISO conversion not working

### ISSUE THREAD

**Issue by hardlevel** [GDX-X/PFS-BatchKit-Manager#43]
Hi!
When I try the option 5 to convert BIN to ISO for PS2 games, is says:
.VCD NOT DETECTED: Please drop .VCD IN POPS FOLDER.

Maybe it's using the wrong function?

**Comment by GDX-X** [comment]
Hey, Ah I forgot to change the message but the function works, put your bin/cue in the CD folder, it will convert them to ISO

I will update it soon

**Comment by hardlevel** [comment]
Nice, thanks!

**Comment by hardlevel** [comment]
confirmed, after adding the images on cd folder it convert to iso

maybe would be nice if the function to add the games to hdd converts bin to iso or install it directly, some hdd managers like winhiip has support for bin format

thanks!

**Comment by GDX-X** [comment]
It already does this automatically

for installing bin/cue files

**Comment by GDX-X** [comment]
FIXED 1.1.8
