### ISSUE TITLE
CFG configuration not being reflected into OPL

### ISSUE THREAD

**Issue by Husky363** [GDX-X/PFS-BatchKit-Manager#46]
Hi, i am running FreeHDDboot and all my backups along with art files and themes are being stored into the HDD . during the PFS transferring the games to HDD i always include downloading and transferring the CFG files however and i can see them via OPL manager windows app  that the modes are being ticked. However, on the PS2 i dont see the modes being enabled as per the config files txt instructions

**Comment by GDX-X** [comment]
Hi, If you talk about compatibility modes, not all of them are enabled but only for certain games that need them to work

**Comment by Husky363** [comment]
> Hi, If you talk about compatibility modes, not all of them are enabled but only for certain games that need them to work

Thank you for your quick reply and yes i am aware the compatiblity modes are working for some games for example devil may cry where mode 1 and 6 are enabled as per the CFG file that has been generated but when i go back to the PS2 console and lunch opl and check the settings of the compatibility mode its off while i have tested the cfg files being addressed correctly to my game version on the opl manager desktop app where it shows the cfg has already modified the compatibility modes. my question is are there any steps to make the CFG files to work on the PS2 as i still have to configure the compatibility modes for certain games by myself

**Comment by GDX-X** [comment]
Yes, some games are not yet in the database of games requiring compatibility.

However, if you have manually added compatibility modes, you must save them in OPL so that it remains saved, you do not need to do anything else

If you want to add them, feel free to open tickets on this repo to add them

https://github.com/GDX-X/PS2-OPL-CFG-Compatibility-Database

**Comment by Husky363** [comment]
i think you have misunderstood what kind of issue i am having . in the PFS manager i downloaded the CFG files for the games i have copied into the HDD. However when i browse OPL on my PS2 the CFG files doesnt take any effect on the games that i downloaded for.

**Comment by GDX-X** [comment]
Have you checked if it is present in the CFG folder of your +OPL partition?

if they are present but there are no descriptions this is normal not all games have descriptions at the moment

**Comment by GDX-X** [comment]
Fixed more db added
