### ISSUE TITLE
Unable to determine disc type File ignored

### ISSUE THREAD

**Issue by NavyGuy81** [GDX-X/PFS-BatchKit-Manager#47]
I am attempting to transfer some of my backups and I receive the following errors:

*ISO: not a PlayStation CD-ROM/DVD-ROM
Warning: Unable to determine disc type File ignored

It is happening to files that are zipped as well as in ISO format.

I'm not sure if it is related but some other files are also displaying:
ERROR: Data Error : *.ISO
but then the file appears to transfer correctly.

**Comment by GDX-X** [comment]
This error appears for several games or just one? if you can give me the name of the game that is causing the problem

**Comment by NavyGuy81** [comment]
![image](https://github.com/GDX-X/PFS-BatchKit-Manager/assets/1802151/556ed3c5-881b-4a38-8544-933ad75c9d90)

This is from my most recent attempt to copy the games over. They are all in the same folder. The first 3 are already extracted ISOs. I did just test out the games that did appear to copy and only FFX-2 is the only one that works(but it's also the only one without the Data Error). Thanks!

**Comment by GDX-X** [comment]
Have you checked the md5s of these games?

This looks like a bad dump

**Comment by NavyGuy81** [comment]
I hadn't, mostly because I thought the odds of multiple games being bad right off the bat was low. It looks like you are correct. Thanks!
