### ISSUE TITLE
Program hangs when downloading art for PS1 games

### ISSUE THREAD

**Issue by CelestialQwert** [GDX-X/PFS-BatchKit-Manager#48]
When I try to download art for PS1 games via the "PS1 Games Shortcut OPL APPS TAB" option, it was getting stuck at "Scanning Games List". I did some poking around and I believe I found the culprit. On [line 6664](https://github.com/GDX-X/PFS-BatchKit-Manager/blob/9ec7868ebe08fa98e550ba36025240c97192e22d/PFS-BatchKit-Manager/!PFS-BatchKit-Manager.bat#L6664C1-L6664C1) I changed `"--partition=__.POPS!choice!"` to `"--partition=!POPSPART!"` and it's now downloading the art without issue.

**Comment by mrkylegp** [comment]
I've got this issue too. 
![image](https://github.com/GDX-X/PFS-BatchKit-Manager/assets/52687659/1ac7af78-d691-40b0-96b6-271ce1d773b6)

**Comment by GDX-X** [comment]
Hi, I fixed this bug but haven't finished the rest yet. a very big update will arrive soon I took a while to release it because I changed a lot of things and added some big new features if you can wait a few more days I plan to release it on July 20 if all is fine

**Comment by GDX-X** [comment]
Fixed
