### ISSUE TITLE
Download ARTs for PS1 OPL APPS Tab freezes 

### ISSUE THREAD

**Issue by Mixinhas** [GDX-X/PFS-BatchKit-Manager#51]
Download of Artworks for PS1 stucking on 
"Scanning Games List: 
----------------------------------------------------"

option used: Yes (For PS1 Games Shortcut OPL APPS TAB)

**Comment by GDX-X** [comment]
Yes this can happen I already have a solution open for this problem

I'm going to correct that but I'm in the process of rewriting the code for downloading the ARTs, something else that will be less complicated to do, I'm thinking of releasing the update at the end of February but I'm not sure yet

so the solution is to modify line 6664 I changed "--partition=__.POPS!choice!" to "--partition=!POPSPART!"

**Comment by Mixinhas** [comment]
It worked, thank you!

**Comment by TrainedLoop** [comment]
thx, this works

**Comment by GDX-X** [comment]
Fixed
