### ISSUE TITLE
Creating Mastercode CHT  -ERROR-

### ISSUE THREAD

**Issue by Bizzy-Shz** [GDX-X/PFS-BatchKit-Manager#53]
I had a problem with creating CHT files for my Games.

After saying yes to the Mastercode question, it will only create 16 files and then comes the ever same error.

![Screenshot 2024-02-18 142503](https://github.com/GDX-X/PFS-BatchKit-Manager/assets/110717923/27f04a08-b1ab-44f6-a558-bf9632f91eca)

I tried three variables of filenames

Final Fantasy X.iso
SCES_504.92.Final Fantasy X.iso
Final Fantasy X - [SCES_504.92].iso

**Comment by GDX-X** [comment]
I already fixed it in the next update I will publish it soon.
but to avoid this restart pfs batchkit manager and try again

**Comment by GDX-X** [comment]
Fixed
