### ISSUE TITLE
ZSO is not working properly

### ISSUE THREAD

**Issue by amxcs** [GDX-X/PFS-BatchKit-Manager#55]
After I convert the iso's with this command (-h) all games work!
`ziso -i (isofilename) -h`

https://www.psx-place.com/threads/testers-needed-open-ps2-loader-with-zso-support-compressed-iso.37223/page-15#post-380529

There is also information about the issue here - https://github.com/ps2homebrew/hdl-dump/issues/71

**Comment by GDX-X** [comment]
pfs batchkit manager uses maxcso to convert the game to zso it is more precise than that in python

**Comment by amxcs** [comment]
I understand, but the games are not working.

`You have to pad the ZSO files before you installing it ([Danixu tools can do that](https://github.com/Danixu/ziso_compressor/releases) or use hex editor to pad it manually).`

**Comment by GDX-X** [comment]
mhh ok I'll check that! thanks

**Comment by amxcs** [comment]
I converted 1100 games with ZISO (with -h command). That's how much they fit on a 2TB hard drive. Then I put them in the DVD folder. Everything is installed easily and automatically.
Of course, I didn't have time to test them all, but of the ones I tried, they all work!

**Comment by GDX-X** [comment]
I will do some testing but So there is no longer a need for mode 1?

**Comment by amxcs** [comment]
It needs Mode1.

But the ISO files I tried to convert (and which needed trim) with pfs batchkit manager (maxcso) didn't work (black screen).
ISO files converted with ZISO and installed with pfs batchkit manager work without problems.

**Comment by GDX-X** [comment]
Ok, I see

Yes you do not need the original iso because pfs batchkit manager decompresses the zso before to obtain the information from the iso and then transfer the zso

**Comment by amxcs** [comment]
This is a very nice feature, because to install all the games at once I would have needed 6TB free.

**Comment by GDX-X** [comment]
Fixed 1.1.9
