### ISSUE TITLE
Can't open the program on a external HDD

### ISSUE THREAD

**Issue by xpdbLEGEND** [GDX-X/PFS-BatchKit-Manager#58]
It just opens for half a second than closes..

I've also a question about the new 1.1.8 update. Does the added HDD cache improves loading time on the PFSBatch Installer, OR on the PS2 itself? And if it's on the PS2 itself, how can this cache differ from the one OPL creates (inside +OPL folder) ?

**Comment by GDX-X** [comment]
Cache helps improve script speed not directly on PS2

If it closes after opening, it means that an antivirus is probably interfering.

**Comment by xpdbLEGEND** [comment]
> Cache helps improve script speed not directly on PS2
> 
> If it closes after opening, it means that an antivirus is probably interfering.

Thank you. Does that mean it loads faster on OPL? Or just on PFS Batch?

**Comment by GDX-X** [comment]
Just PFS Batchkit Manager
