### ISSUE TITLE
OPL & uLE not work on PSBBN

### ISSUE THREAD

**Issue by Majortomm0** [GDX-X/PFS-BatchKit-Manager#59]
Hello, I tried to install OPL (latest and Stable) and uLE (both versions) so that they would work from BBN. ​​Unfortunately, when I try to run the application, an error appears. I checked on two different hard drives with the same result. Is there anything I can do to fix this problem?

**Comment by GDX-X** [comment]
Hi, yes it's normal I made modifications with the database and therefore this version 1.1.8 is broken I will publish 1.1.9 I have made a lot of changes everything will be fixed

**Comment by Majortomm0** [comment]
Thank you for your reply. It's too bad that the function doesn't work, I didn't pay attention to the description, sorry.
Is there any other way to add uLe and other applications so that they can be run from the BBN level?

**Comment by GDX-X** [comment]
Yes wait until 05 I will publish the update

**Comment by Majortomm0** [comment]
yeah, thanks for what you do. I made a small donation via Ko-fi. Thanks

**Comment by GDX-X** [comment]
Thank you I appreciate it <3
