### ISSUE TITLE
Bundled pfsshell doesn't support more than 32GB partitions.

### ISSUE THREAD

**Issue by Br3ttl3y** [GDX-X/PFS-BatchKit-Manager#6]
The bundled PFSSHELL only supports single partitions up to 32GB.

Steps to reproduce:
1. Open command prompt to your `%Repository_Root%\BAT`
2. `pfsshell.exe`
3. `device \\.\PhysicalDriveX` Where X is your PS2 drive
4. `mkpart Test 65536`

Result:
hdd: Errror: Invalid partition size, 64G
(!) test: Invalid argument.
(!) Exit code is -22

Resolution:
1. Download latest debug build from pfsshell `https://github.com/ps2homebrew/pfsshell/releases/download/latest/pfsshell-v1.1.1-win32.7z`
2. Replace `%Repository_Root\BAT\pfsshell.exe`
3. Rerun the above steps.  Replace `65536` with `64G`

Result:
Partitions are created successfully.

**Comment by GDX-X** [comment]
Thank you for your report I was aware of the partition creation bug but I had not seen the pfsshell update..

However I tried the new pfsshell but I cannot create a partition, did you succeed?

**Comment by israpps** [comment]
> Thank you for your report I was aware of the partition creation bug but I had not seen the pfsshell update..
> 
> However I tried the new pfsshell but I cannot create a partition, did you succeed?

Don't forget that the DLL can also change

**Comment by GDX-X** [comment]
> > Thank you for your report I was aware of the partition creation bug but I had not seen the pfsshell update..
> > However I tried the new pfsshell but I cannot create a partition, did you succeed?
> 
> Don't forget that the DLL can also change


Yes I tried the pfsshell directly me when I create a partition I have this error

![989321a92e1a171fa9b4d69b2c40fead](https://user-images.githubusercontent.com/22562949/151186955-3ef71ec9-2b2d-4929-81a9-c573d50f7552.png)

**Comment by Br3ttl3y** [comment]
You are able to use the correct nomenclature in the new update.  You should use 64G instead of 65536.  I thought they would have kept it for backward compatibility.  I guess not.

**Comment by GDX-X** [comment]
Ah!! Thank you! I had not tried with the 'G'. I will update it in the next update because I need to change some commands because some commands have been removed or changed

**Comment by Br3ttl3y** [comment]
I figured as much.  While you're there you can fix a typo it shows 1G twice.  Once for 1024 and another for 2048. :)
