### ISSUE TITLE
Unable to create shortcuts for PS1 games in APP TAB

### ISSUE THREAD

**Issue by b3rsrk0** [GDX-X/PFS-BatchKit-Manager#60]
Version: 1.1.9

Basically the issue I am facing could be seen on the following images:

![Screenshot 2024-10-14 165206](https://github.com/user-attachments/assets/137940bd-ab24-4f0a-a7c9-cda74399a667)

Either 1 or 2

![Capture](https://github.com/user-attachments/assets/7f4a6352-4081-4897-ac4f-e7daa5dcd278)
![Screenshot 2024-10-14 165126](https://github.com/user-attachments/assets/de871abc-136b-4abb-a6b3-3fe0178d2e19)
![Capture1](https://github.com/user-attachments/assets/94fcda96-644b-48f4-82d8-233106038b9c)

Version: 1.1.8 just crashes on "Creating Queue"

![Screenshot 2024-10-14 164032](https://github.com/user-attachments/assets/4a1d306f-290e-46cb-8cf0-65c222002b7d)

~Thank you

**Comment by GDX-X** [comment]
I forgot to close a parenthesis 😅

Fixed, you can redownload version 1.1.9

**Comment by b3rsrk0** [comment]
Well, thanks. Now it reads the game list I guess but doesn't create shortcuts. The process ends with this:

![Capture](https://github.com/user-attachments/assets/100be000-27d3-4f5c-89c1-cd80b02d8999)

**Comment by GDX-X** [comment]
PS1 games need to have their GameID at the beginning to be detected, for example: SLUS_123.45.MyGame.VCD

**Comment by b3rsrk0** [comment]
so, the option that offers to add prefixes before the game image names is redundant? :) 
because if I say "N" on "add prefixes" when moving a new image to __.POPS either way I would be forced to add them in future

**Comment by Unixware** [comment]
> so, the option that offers to add prefixes before the game image names is redundant? :) because if I say "N" on "add prefixes" when moving a new image to __.POPS either way I would be forced to add them in future

when devs have no clue... FFS @GDX-X
