### ISSUE TITLE
How to add artworks for PS1 games?

### ISSUE THREAD

**Issue by b3rsrk0** [GDX-X/PFS-BatchKit-Manager#61]
This is more "need help" rather than an issue. 
If ps1 games are successfully transferred onto __.POPS partition the **OPL Manager** doesn't see any of these games nor transferred APPS, PS2 games only. 
So I am using **PFS-BatchKit-Manager** as follows:

![Capture](https://github.com/user-attachments/assets/9a811bc9-bce1-4048-a9eb-e5b22c5af0c0)
![Capture1](https://github.com/user-attachments/assets/cdc4869a-d5ec-4545-9c28-b5fd06b703a1)
![Capture2](https://github.com/user-attachments/assets/e955d236-54ab-4aeb-a6c8-2acdd951e49a)

Which URL it intents to connect to?

**Comment by GDX-X** [comment]
archive.org is currently down so you need the ART.zip file to be able to update the ARTs locally

https://www.mediafire.com/folder/ctlaqqr279qkar1,gyb60y1g13wrdl2/shared

Put ART.zip in the root of pfs batchkit manager

**Comment by b3rsrk0** [comment]
Now it works, However the artworks does not displayed for APPS what so ever. I think this is a problem of the latest version of OPL.
~Thank you

**Comment by xpdbLEGEND** [comment]
I’m having thr same exact issue as described above, the ART doesn’t show on APPS tab. I’m using OPL 1.2.0 2049 beta.

**Comment by GDX-X** [comment]
I haven't tested version 2049 so there may be a problem with this version. but did you say yes to this option?

![c6b3096173817e8927f09d343d7fc095](https://github.com/user-attachments/assets/1aff51a0-37d2-4d01-ac6c-b58c0f669348)

**Comment by xpdbLEGEND** [comment]
Yes, I said yes . 
![213123324](https://github.com/user-attachments/assets/cea17bbd-e44c-4dc5-8b00-137c242ebfa8)

I've just tested with OPL 1.1.0 and it didn't work either

**Comment by GDX-X** [comment]
Fixed you can redownload 1.1.9

**Comment by xpdbLEGEND** [comment]
Thank you very very much, that solved the issue! btw, is there an option for downloading only CFG for VCD games listed as apps on OPL?

**Comment by GDX-X** [comment]
> Thank you very very much, that solved the issue! btw, is there an option for downloading only CFG for VCD games listed as apps on OPL? Without noticing I've downloaded and installed those cfg in French (I'm not French..) so I wanted to update to English.

Yes, you just need to create the shortcuts for the PS1 games, the CFGs will be added automatically
