### ISSUE TITLE
transfers ps1 games

### ISSUE THREAD

**Issue by mmhgithub** [GDX-X/PFS-BatchKit-Manager#7]
Hi,
I am using an old PC with Windows 7 and I have no internet access to this PC.
When I transfer ps1 games, I get nicely into the menu that says:
VCD installation:
      creation Que
      install vcd.

But from this point it stalls

Do I need wifi access to continue?
Or I am simply using the program incorrectly.

I use the conversion of BIN/CUE to VCD, 
I use OPL to correct the vcd files
 
I then transfer:
SCUS_942.36 Tomba
SLUS_007.39 Future Cop L, A, P.D

Tomba is possible to transfer, 
But Future Cop, is simply not working. 

Best regards
Mikkel from Denmark.

**Comment by GDX-X** [comment]
Hello, You don't need wifi to install .VCDs if you're stuck it's probably because the size of your partition is not big enough to copy .VCDs to.

**Comment by mmhgithub** [comment]
Hi, 
you are totally right. 
thank you! 
very much appreciate.

Nice feature thow would be to give some kind of a progress bar. 
And maybe a feedback of the partition size config.
Maybe also a log about how fare this proces went.
Or maybe just telling that the proces has stoped. 

What i do now, is opening a new manager, and extracting the gamelist to see the progress. 
I am currently oploading 39 games.

Thank you for your time.

**Comment by israpps** [comment]
> Hi, you are totally right. thank you! very much appreciate.
> 
> Nice feature thow would be to give some kind of a progress bar. And maybe a feedback of the partition size config. Maybe also a log about how fare this proces went. Or maybe just telling that the proces has stoped.
> 
> What i do now, is opening a new manager, and extracting the gamelist to see the progress. I am currently oploading 39 games.
> 
> Thank you for your time.

Progress bar is something you should ask on pfsshell

**Comment by zulc22** [comment]
@GDX-X you need to close issues that are resolved, you can't always expect the OP to do it
