### ISSUE TITLE
!COPY_TO_USB_ROOT folder is empty

### ISSUE THREAD

**Issue by hardlevel** [GDX-X/PFS-BatchKit-Manager#8]
When I try to hack hdd, the folder !COPY_TO_USB_ROOT is empty and after the conclusion of the proccess on the program, it says that the system could not find the specified path

**Comment by GDX-X** [comment]
I'll take a look at this I'll deploy an update tonight

**Comment by hardlevel** [comment]
ok thanks!

**Comment by GDX-X** [comment]
But if you want to continue the hack you can download FreeMcBoot 1.66 Manually

HERE > https://github.com/israpps/FreeMcBoot-Installer/releases

**Comment by hardlevel** [comment]
I`m recording a tutorial, for this purpose, would be better if I could do all the proccess directly with your app

**Comment by GDX-X** [comment]
Yes indeed I will update this soon

**Comment by GDX-X** [comment]
I just modified try with the new

**Comment by hardlevel** [comment]
ok thanks I`ll try

**Comment by hardlevel** [comment]
not working yet, now it give me this error:

'"E:\PFS_BatchKit_Manager_v1.0.7\\!COPY_TO_USB_ROOT\README.txt"' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

I see two slashes in the path, it says that isn't recognizes as an internal command ou external, an operative program or a batch file

**Comment by GDX-X** [comment]
Strange me I don't have that problem maybe the slashes

**Comment by GDX-X** [comment]
I'm editing this to see. because for me it works

**Comment by GDX-X** [comment]
You can try again sorry for this inconvenience

**Comment by hardlevel** [comment]
do you belive me if I say that I got the same error? did you changed the file on releades? the last update is from 1 hour ago

**Comment by GDX-X** [comment]
Yes I changed it directly in the file without mentioning it you can download it

**Comment by hardlevel** [comment]
I did, but the error persists

**Comment by GDX-X** [comment]
Do you have discord?

**Comment by hardlevel** [comment]
yes

**Comment by GDX-X** [comment]
GDX#5466
